export const METHOD_TYPE = {
    get: "get",
    post: "post",
    put: "put",
    delete: "delete",
};

export const API_ENDPOINTS = {
  adminLogin: "adminlogin",
  studentLogin: "studentlogin",
  companyLogin: "companylogin",
  changepassword: "changepassword",
  department: "departments",
  academicyeardata: "academicyeardata",
  companylist: "companylist",
  overallcompanydata: "overallcompanydata",
  donutCount: "donutgraphdata?department_id=",
  downloadtemplate: "downloadtemplate",
  registerbulkemployee: "registerbulkemployee/",
  deleteStudent: "deletestudent/",
  allcompanylistforstudent: "allcompanylistforstudent/",
  studentdata: "studentdata/",
  studentprofileupdate: "studentprofileupdate",
  ongoingprocess: "ongoingprocess/",
  studentapplied: "studentapplied",
  admindataupdate: "admindataupdate/",
  getnotification: "getnotification/",
  companyIdApplications: "applications",
  getNotficationTemplate: "notification-template?placement_status=",
  createnotification: "createnotification",
  companyregistration: "companyregistration",
  getcompany: "getcompany/",
  updatecompany: "updatecompany/",
};

